version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_book_db
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dev_book
    ports:
      - '3306:3306'
    volumes:
      - ./database/mysql:/var/lib/mysql