// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Followers        string
	Publication      string
	User             string
	PrismaMigrations string
}{
	Followers:        "Followers",
	Publication:      "Publication",
	User:             "User",
	PrismaMigrations: "_prisma_migrations",
}
