// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUSERS(t *testing.T) {
	t.Parallel()

	query := USERS()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUSERSDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUSERSQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := USERS().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUSERSSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := USERSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUSERSExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := USERExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if USER exists: %s", err)
	}
	if !e {
		t.Errorf("Expected USERExists to return true, but got false.")
	}
}

func testUSERSFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	uSERFound, err := FindUSER(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if uSERFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUSERSBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = USERS().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUSERSOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := USERS().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUSERSAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	uSEROne := &USER{}
	uSERTwo := &USER{}
	if err = randomize.Struct(seed, uSEROne, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}
	if err = randomize.Struct(seed, uSERTwo, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = uSEROne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = uSERTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := USERS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUSERSCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	uSEROne := &USER{}
	uSERTwo := &USER{}
	if err = randomize.Struct(seed, uSEROne, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}
	if err = randomize.Struct(seed, uSERTwo, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = uSEROne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = uSERTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func uSERBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func uSERAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *USER) error {
	*o = USER{}
	return nil
}

func testUSERSHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &USER{}
	o := &USER{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, uSERDBTypes, false); err != nil {
		t.Errorf("Unable to randomize USER object: %s", err)
	}

	AddUSERHook(boil.BeforeInsertHook, uSERBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	uSERBeforeInsertHooks = []USERHook{}

	AddUSERHook(boil.AfterInsertHook, uSERAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	uSERAfterInsertHooks = []USERHook{}

	AddUSERHook(boil.AfterSelectHook, uSERAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	uSERAfterSelectHooks = []USERHook{}

	AddUSERHook(boil.BeforeUpdateHook, uSERBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	uSERBeforeUpdateHooks = []USERHook{}

	AddUSERHook(boil.AfterUpdateHook, uSERAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	uSERAfterUpdateHooks = []USERHook{}

	AddUSERHook(boil.BeforeDeleteHook, uSERBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	uSERBeforeDeleteHooks = []USERHook{}

	AddUSERHook(boil.AfterDeleteHook, uSERAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	uSERAfterDeleteHooks = []USERHook{}

	AddUSERHook(boil.BeforeUpsertHook, uSERBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	uSERBeforeUpsertHooks = []USERHook{}

	AddUSERHook(boil.AfterUpsertHook, uSERAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	uSERAfterUpsertHooks = []USERHook{}
}

func testUSERSInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUSERSInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(uSERColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUSERToManyFollowerUSERS(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into `FOLLOWERS` (`user_id`, `follower_id`) values (?, ?)", a.ID, b.ID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into `FOLLOWERS` (`user_id`, `follower_id`) values (?, ?)", a.ID, c.ID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.FollowerUSERS().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ID == b.ID {
			bFound = true
		}
		if v.ID == c.ID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := USERSlice{&a}
	if err = a.L.LoadFollowerUSERS(ctx, tx, false, (*[]*USER)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FollowerUSERS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.FollowerUSERS = nil
	if err = a.L.LoadFollowerUSERS(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FollowerUSERS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testUSERToManyUserUSERS(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, uSERDBTypes, false, uSERColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	_, err = tx.Exec("insert into `FOLLOWERS` (`follower_id`, `user_id`) values (?, ?)", a.ID, b.ID)
	if err != nil {
		t.Fatal(err)
	}
	_, err = tx.Exec("insert into `FOLLOWERS` (`follower_id`, `user_id`) values (?, ?)", a.ID, c.ID)
	if err != nil {
		t.Fatal(err)
	}

	check, err := a.UserUSERS().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ID == b.ID {
			bFound = true
		}
		if v.ID == c.ID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := USERSlice{&a}
	if err = a.L.LoadUserUSERS(ctx, tx, false, (*[]*USER)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.UserUSERS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.UserUSERS = nil
	if err = a.L.LoadUserUSERS(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.UserUSERS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testUSERToManyAuthPUBLICATIONS(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c PUBLICATION

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, pUBLICATIONDBTypes, false, pUBLICATIONColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, pUBLICATIONDBTypes, false, pUBLICATIONColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.AuthID = a.ID
	c.AuthID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.AuthPUBLICATIONS().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.AuthID == b.AuthID {
			bFound = true
		}
		if v.AuthID == c.AuthID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := USERSlice{&a}
	if err = a.L.LoadAuthPUBLICATIONS(ctx, tx, false, (*[]*USER)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AuthPUBLICATIONS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.AuthPUBLICATIONS = nil
	if err = a.L.LoadAuthPUBLICATIONS(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.AuthPUBLICATIONS); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testUSERToManyAddOpFollowerUSERS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*USER{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*USER{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddFollowerUSERS(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.UserUSERS[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.UserUSERS[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.FollowerUSERS[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.FollowerUSERS[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.FollowerUSERS().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testUSERToManySetOpFollowerUSERS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*USER{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetFollowerUSERS(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.FollowerUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetFollowerUSERS(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.FollowerUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.UserUSERS) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.UserUSERS) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.UserUSERS[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.UserUSERS[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.FollowerUSERS[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.FollowerUSERS[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testUSERToManyRemoveOpFollowerUSERS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*USER{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddFollowerUSERS(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.FollowerUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveFollowerUSERS(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.FollowerUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.UserUSERS) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.UserUSERS) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.UserUSERS[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.UserUSERS[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.FollowerUSERS) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.FollowerUSERS[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.FollowerUSERS[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testUSERToManyAddOpUserUSERS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*USER{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*USER{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddUserUSERS(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if first.R.FollowerUSERS[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}
		if second.R.FollowerUSERS[0] != &a {
			t.Error("relationship was not added properly to the slice")
		}

		if a.R.UserUSERS[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.UserUSERS[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.UserUSERS().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testUSERToManySetOpUserUSERS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*USER{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetUserUSERS(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.UserUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetUserUSERS(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.UserUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	// The following checks cannot be implemented since we have no handle
	// to these when we call Set(). Leaving them here as wishful thinking
	// and to let people know there's dragons.
	//
	// if len(b.R.FollowerUSERS) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	// if len(c.R.FollowerUSERS) != 0 {
	// 	t.Error("relationship was not removed properly from the slice")
	// }
	if d.R.FollowerUSERS[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}
	if e.R.FollowerUSERS[0] != &a {
		t.Error("relationship was not added properly to the slice")
	}

	if a.R.UserUSERS[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.UserUSERS[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testUSERToManyRemoveOpUserUSERS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e USER

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*USER{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddUserUSERS(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.UserUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveUserUSERS(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.UserUSERS().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if len(b.R.FollowerUSERS) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if len(c.R.FollowerUSERS) != 0 {
		t.Error("relationship was not removed properly from the slice")
	}
	if d.R.FollowerUSERS[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.FollowerUSERS[0] != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if len(a.R.UserUSERS) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.UserUSERS[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.UserUSERS[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testUSERToManyAddOpAuthPUBLICATIONS(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a USER
	var b, c, d, e PUBLICATION

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, uSERDBTypes, false, strmangle.SetComplement(uSERPrimaryKeyColumns, uSERColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*PUBLICATION{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, pUBLICATIONDBTypes, false, strmangle.SetComplement(pUBLICATIONPrimaryKeyColumns, pUBLICATIONColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*PUBLICATION{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddAuthPUBLICATIONS(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.AuthID {
			t.Error("foreign key was wrong value", a.ID, first.AuthID)
		}
		if a.ID != second.AuthID {
			t.Error("foreign key was wrong value", a.ID, second.AuthID)
		}

		if first.R.Auth != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Auth != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.AuthPUBLICATIONS[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.AuthPUBLICATIONS[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.AuthPUBLICATIONS().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testUSERSReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUSERSReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := USERSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUSERSSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := USERS().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	uSERDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`, `Nick`: `varchar`, `Email`: `varchar`, `Password`: `varchar`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`}
	_           = bytes.MinRead
)

func testUSERSUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(uSERPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(uSERAllColumns) == len(uSERPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUSERSSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(uSERAllColumns) == len(uSERPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &USER{}
	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, uSERDBTypes, true, uSERPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(uSERAllColumns, uSERPrimaryKeyColumns) {
		fields = uSERAllColumns
	} else {
		fields = strmangle.SetComplement(
			uSERAllColumns,
			uSERPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := USERSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUSERSUpsert(t *testing.T) {
	t.Parallel()

	if len(uSERAllColumns) == len(uSERPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLUSERUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := USER{}
	if err = randomize.Struct(seed, &o, uSERDBTypes, false); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert USER: %s", err)
	}

	count, err := USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, uSERDBTypes, false, uSERPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize USER struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert USER: %s", err)
	}

	count, err = USERS().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
